### ISSUE TITLE
[Feature request] Possibility for default plugin configuration via qgis_global_settings.ini

### ISSUE THREAD

**Issue by JPPauly** [qgisinspiretools/qgis-wfs20-client-plugin#22]
It would be really useful to be able to load a default plugin config via qgis_global_settings.ini as long as there is no user specific config. Using QgsSettings function instead of QSettings would support that. 

I created a [pull request](https://github.com/qgisinspiretools/qgis-wfs20-client-plugin/pull/21) for your consideration.

**Comment by ejn** [comment]
Nice idea. I'll check the PR when I get a minute, but at first glance it looks good.

**Comment by JPPauly** [comment]
I just commited a fix into my pull request. Q(gs)Settings seems to be inconsistent in what datatype is returned by value(). Sometimes its Bool True/False and sometimes its String "true"/"false". Checking for both seems to work in all cases.

**Comment by ejn** [comment]
PR #21 is merged. Many thanks!

I'll prepare a release with this in it and upload to the QGIS Repository. Will close this ticket once the new version is available there.

**Comment by ejn** [comment]
[Release 0.9.11](/qgisinspiretools/qgis-wfs20-client-plugin/releases/tag/0.9.11) is now waiting for approval in the QGIS Plugins Repo.

**Comment by ejn** [comment]
0.9.11 was approved (a long time ago!), so closing this now.
