### ISSUE TITLE
WFS ALKIS und ATKIS aaa-modell-basiert (NW und BB )

### ISSUE THREAD

**Issue by MathiasRedlich** [qgisinspiretools/qgis-wfs20-client-plugin#24]
Mit der Version 0.9.11 vom WFS Client können Daten aus den unten genannten WFS ALKIS oder ATKIS von Nordrhein-Westfalen und Brandenburg nicht mehr zum QGIS (3.10 und 3.16) hinzugefügt und angezeigt werden:

WFS ALKIS NW aaa-modell-basiert: https://www.wfs.nrw.de/geobasis/wfs_nw_alkis_aaa-modell-basiert
WFS ATKIS NW aaa-modell-basiert: https://www.wfs.nrw.de/geobasis/wfs_nw_atkis-basis-dlm_aaa-modell-basiert

WFS ALKIS BB aaa-modell-basiert: https://isk.geobasis-bb.de/ows/alkis_sf_wfs?

Mit der Version 0.9.9 vom WFS Client (und mit QGIS 3.10) funktionieren die drei o.g. Dienste (aaa-modell-basiert) ohne Probleme.
Der WFS ALKIS vereinfacht von NW (https://www.wfs.nrw.de/geobasis/wfs_nw_alkis_vereinfacht) funktioniert auch in der Version 0.9.11.

**Comment by JuergenWeichand** [comment]
Ich habe die Tage eine ähnliche Beobachtung gemacht. Wird der Schalter `Resolve elements xlink:href` in der Konfiguration des Plugins verwendet?

**Comment by JuergenWeichand** [comment]
Wie schaut denn das Ergebnis aus (ggf. Screenshot)?

**Comment by JuergenWeichand** [comment]
Nachdem sich meine Beobachtung explizit auf das Reference-Resolving bezieht habe ich ein separates Ticket aufgemacht: https://github.com/qgisinspiretools/qgis-wfs20-client-plugin/issues/25

**Comment by MathiasRedlich** [comment]
Bei einer Abfrage ohne Boundary Box wird ein leerer Layer namens "AX_Flurstueck" hinzugefügt. Im QGIS Protokoll steht unter OGR:  "WARNING    OGR[2] Fehler 1: NAS: Skipping geometry without feature" (vgl. beigefügtem Screenshot).
Unter ...\AppData\Local\Temp\wfs20client wird eine gml erzeugt, die die gewünschten Daten eigentlich enthält. Beim nachträglichen Hinzufügen des Layers erhalte ich leider ebenfalls einen leeren Layer.

**Comment by JuergenWeichand** [comment]
Ist der Schalter "Disable NAS Detection" in der Konfiguration gesetzt? Falls nicht bitte ausprobieren.

**Comment by MathiasRedlich** [comment]
Habe es mit dem Schalter "Disable NAS Detection" ausprobiert. Damit hat es auch mit der Version 0.9.11 bei den oben genannten WFS aaa-modell-basiert funktioniert. War mir nicht bekannt den Schalter zu setzen, sorry. Vielen Dank für die Lösung.

**Comment by JuergenWeichand** [comment]
Anbei noch ein paar Hintergrundinformationen: 

GDAL/OGR erkennt die WFS-Response als NAS. Jedoch erwartet es die klassischen NAS-Container und nicht den GML-Containter der GetFeature-Response. Dies führt zu einem fehlerhaften Import. 

Mit dem Schalter `Disable NAS Detection` wird die Verwendung des universellen GML-Treibers erzwungen. 

Sofern das Problem gelöst ist bitte Ticket schließen. 

Viele Grüße
Jürgen

**Comment by MathiasRedlich** [comment]
Vielen Dank für die Informationen. Ticket wird geschlossen.
